export const Questions = [
  {
    prompt: "Which of the following is the correct way to link an external CSS file to an HTML document?",
    optionA: '<link rel="stylesheet" href="styles.css">',
    optionB: '<style src="styles.css"></style>',
    optionC: '<script src="styles.css"></script>',
    optionD: '<stylesheet href="styles.css"></stylesheet>',
    answer: "optionA",
  },
  {
    prompt: "Which of this is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "MC-03",
    optionD: "Java",
    answer: "optionC",
  },
  {
    prompt: "Which of this is not a JavaScript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    answer: "optionD",
  },
  {
    prompt: "What does HTML stand for?",
    optionA: "HyperText Markup Language",
    optionB: "HighText Markup Language",
    optionC: "HyperText Markdown Language",
    optionD: "HighText Markdown Language",
    answer: "optionA",
  },
  {
    prompt: "Which CSS property is used to change the background color of an element?",
    optionA: "background-color",
    optionB: "bg-color",
    optionC: "color-background",
    optionD: "background",
    answer: "optionA",
  },
  {
    prompt: "What is the correct syntax to create a function in JavaScript?",
    optionA: "function myFunction() { }",
    optionB: "function:myFunction() { }",
    optionC: "create function myFunction() { }",
    optionD: "myFunction() = function { }",
    answer: "optionA",
  },
  {
    prompt: "What will `console.log(typeof NaN)` output in JavaScript?",
    optionA: "number",
    optionB: "undefined",
    optionC: "object",
    optionD: "NaN",
    answer: "optionA",
  },
  {
    prompt: "How do you add a comment in JavaScript?",
    optionA: "<!-- This is a comment -->",
    optionB: "/* This is a comment */",
    optionC: "// This is a comment",
    optionD: "# This is a comment",
    answer: "optionC",
  },
  {
    prompt: "Which HTTP method is used to retrieve data from a server?",
    optionA: "POST",
    optionB: "GET",
    optionC: "PUT",
    optionD: "DELETE",
    answer: "optionB",
  },
  {
    prompt: "What is a CSS preprocessor?",
    optionA: "A tool that processes CSS files before they are served to the browser",
    optionB: "A program that converts CSS into JavaScript",
    optionC: "A JavaScript library that enhances CSS styling",
    optionD: "A tool for debugging CSS code",
    answer: "optionA",
  },
  {
    prompt: "What does API stand for?",
    optionA: "Application Programming Interface",
    optionB: "Applied Programming Interface",
    optionC: "Application Protocol Integration",
    optionD: "Applied Protocol Interface",
    answer: "optionA",
  },
  {
    prompt: "Which HTML element is used to define a section in a web page?",
    optionA: "<section>",
    optionB: "<div>",
    optionC: "<article>",
    optionD: "<container>",
    answer: "optionA",
  },
  {
    prompt: "What is the purpose of media queries in CSS?",
    optionA: "To apply styles based on the device's screen size and other characteristics",
    optionB: "To create animations in CSS",
    optionC: "To connect to external APIs",
    optionD: "To manage server-side data",
    answer: "optionA",
  },
  {
    prompt: "What is a breakpoint in responsive design?",
    optionA: "A point at which the layout of a webpage changes based on the viewport size",
    optionB: "A section of code that causes a page to break",
    optionC: "A feature that helps with debugging",
    optionD: "A method to optimize images for different devices",
    answer: "optionA",
  },
  {
    prompt: "Which meta tag is used to set the viewport width for responsive web design?",
    optionA: '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    optionB: '<meta name="viewport" content="width=100%">',
    optionC: '<meta name="viewport" content="initial-scale=1.0">',
    optionD: '<meta name="viewport" content="device-width=1.0">',
    answer: "optionA",
  },
  {
    prompt: "Which of the following is NOT a valid HTML5 input type?",
    optionA: "text",
    optionB: "date",
    optionC: "color",
    optionD: "email",
    answer: "optionD",
  }
];
